export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';
export const PULL_BLOCK_DATA_START = 'PULL_BLOCK_DATA_START';
export const PULL_BLOCK_DATA_SUCCESS = 'PULL_BLOCK_DATA_SUCCESS';
export const PULL_BLOCK_DATA_FAILURE = 'PULL_BLOCK_DATA_FAILURE';